version: '3.8'

services:

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: development
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: ${MONGO_URI}

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: